---
title: Svengali
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: josh@tabansi.com
description: |
  Svengali is an internationally renown creative agency that does amazing interior design and furniture manufacturing.
baseurl: ''
url: http://svengalidesigns.com
twitter_username: svengalidesigns
github_username: tabansi-js
markdown: kramdown
