# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Svengali
email: josh@tabansi.com
description: > # this means to ignore newlines until "baseurl:"
    Svengali is an internationally renown creative agency that does amazing interior design and furniture manufacturing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://svengalidesigns.com" # the base hostname & protocol for your site
twitter_username: svengalidesigns
github_username:  tabansi-js

# Build settings
markdown: kramdown
